name: ibs
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - pip:
    - ydata-profiling
    - pycaret[all]
    - scikit-learn-intelex
    - jupyter
    - ipykernel
    - openpyxl
    - pyreadstat
    - pingouin
    - shap
    - xgboost
    - scikit-plot

# To create the ibs environment
# conda env update -f environment.yml  # To create the named environment from the file

# To update the ibs environment (if new package versions become available):
#conda update -n ibs --all        # To update all packages in the named environment

# To remove and reinstall the ibs environment (if installation problems):
#conda deactivate
#conda env remove -n ibs
#   <fix installation>
# Then, recreate the conda environment ibs as above
